/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BeneficiariesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BeneficiariesApiTests
    {
        private BeneficiariesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BeneficiariesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BeneficiariesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BeneficiariesApi
            //Assert.IsInstanceOfType(typeof(BeneficiariesApi), instance, "instance is a BeneficiariesApi");
        }

        
        /// <summary>
        /// Test V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePut
        /// </summary>
        [Test]
        public void V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string GTN = null;
            //string transID = null;
            //DoChangeNameModelUpdate changeNameModel = null;
            //instance.V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePut(GTN, transID, changeNameModel);
            
        }
        
        /// <summary>
        /// Test V1PaymentsTransfersChangeNameByChangeIDGet
        /// </summary>
        [Test]
        public void V1PaymentsTransfersChangeNameByChangeIDGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string changeID = null;
            //var response = instance.V1PaymentsTransfersChangeNameByChangeIDGet(changeID);
            //Assert.IsInstanceOf<GetChangeNameStatusModelResponse> (response, "response is GetChangeNameStatusModelResponse");
        }
        
    }

}
