/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BillsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BillsApiTests
    {
        private BillsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BillsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BillsApi
            //Assert.IsInstanceOfType(typeof(BillsApi), instance, "instance is a BillsApi");
        }

        
        /// <summary>
        /// Test V1PaymentsBillsPost
        /// </summary>
        [Test]
        public void V1PaymentsBillsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DoBillPaymentModelCreated doBillPaymentModel = null;
            //instance.V1PaymentsBillsPost(doBillPaymentModel);
            
        }
        
        /// <summary>
        /// Test V1PaymentsBillsRequestsByTransIDGet
        /// </summary>
        [Test]
        public void V1PaymentsBillsRequestsByTransIDGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string transID = null;
            //int? sIdType = null;
            //string sIdNum = null;
            //string sFirstName = null;
            //string sLastName = null;
            //string bCountry = null;
            //string bCurrency = null;
            //double? bAmount = null;
            //string bIssuerCode = null;
            //string bAccNum = null;
            //var response = instance.V1PaymentsBillsRequestsByTransIDGet(transID, sIdType, sIdNum, sFirstName, sLastName, bCountry, bCurrency, bAmount, bIssuerCode, bAccNum);
            //Assert.IsInstanceOf<DoBillInquiryModelResponse> (response, "response is DoBillInquiryModelResponse");
        }
        
    }

}
