/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FeesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FeesApiTests
    {
        private FeesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FeesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FeesApi
            //Assert.IsInstanceOfType(typeof(FeesApi), instance, "instance is a FeesApi");
        }

        
        /// <summary>
        /// Test V1PaymentsFeesGet
        /// </summary>
        [Test]
        public void V1PaymentsFeesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? bAccType = null;
            //string currFrom = null;
            //string currTo = null;
            //double? trxValue = null;
            //var response = instance.V1PaymentsFeesGet(bAccType, currFrom, currTo, trxValue);
            //Assert.IsInstanceOf<GetTrxFeeModelResponse> (response, "response is GetTrxFeeModelResponse");
        }
        
    }

}
