/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SupportedEntitiesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SupportedEntitiesApiTests
    {
        private SupportedEntitiesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SupportedEntitiesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SupportedEntitiesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SupportedEntitiesApi
            //Assert.IsInstanceOfType(typeof(SupportedEntitiesApi), instance, "instance is a SupportedEntitiesApi");
        }

        
        /// <summary>
        /// Test V1PaymentsSupportedentitiesByListnameGet
        /// </summary>
        [Test]
        public void V1PaymentsSupportedentitiesByListnameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string listname = null;
            //var response = instance.V1PaymentsSupportedentitiesByListnameGet(listname);
            //Assert.IsInstanceOf<GetTrxFeeModelResponse> (response, "response is GetTrxFeeModelResponse");
        }
        
    }

}
