/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TransfersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TransfersApiTests
    {
        private TransfersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TransfersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransfersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TransfersApi
            //Assert.IsInstanceOfType(typeof(TransfersApi), instance, "instance is a TransfersApi");
        }

        
        /// <summary>
        /// Test V1PaymentsTransfersByGTNGet
        /// </summary>
        [Test]
        public void V1PaymentsTransfersByGTNGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string GTN = null;
            //var response = instance.V1PaymentsTransfersByGTNGet(GTN);
            //Assert.IsInstanceOf<GetTrxStatusModel> (response, "response is GetTrxStatusModel");
        }
        
        /// <summary>
        /// Test V1PaymentsTransfersByGTNRequestsByRSPRequestIDDoCancellationPost
        /// </summary>
        [Test]
        public void V1PaymentsTransfersByGTNRequestsByRSPRequestIDDoCancellationPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string GTN = null;
            //string rSPRequestID = null;
            //var response = instance.V1PaymentsTransfersByGTNRequestsByRSPRequestIDDoCancellationPost(GTN, rSPRequestID);
            //Assert.IsInstanceOf<DoCancellationModelDeleted> (response, "response is DoCancellationModelDeleted");
        }
        
        /// <summary>
        /// Test V1PaymentsTransfersDoCancellationByCancellationIDGet
        /// </summary>
        [Test]
        public void V1PaymentsTransfersDoCancellationByCancellationIDGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string cancellationID = null;
            //var response = instance.V1PaymentsTransfersDoCancellationByCancellationIDGet(cancellationID);
            //Assert.IsInstanceOf<GetCancellationStatusModelResponse> (response, "response is GetCancellationStatusModelResponse");
        }
        
        /// <summary>
        /// Test V1PaymentsTransfersPost
        /// </summary>
        [Test]
        public void V1PaymentsTransfersPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DoTransferModel doTransferModel = null;
            //instance.V1PaymentsTransfersPost(doTransferModel);
            
        }
        
        /// <summary>
        /// Test V1PaymentsTransfersRequestsByTransIDGet
        /// </summary>
        [Test]
        public void V1PaymentsTransfersRequestsByTransIDGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string transID = null;
            //var response = instance.V1PaymentsTransfersRequestsByTransIDGet(transID);
            //Assert.IsInstanceOf<GetTrxStatusModel> (response, "response is GetTrxStatusModel");
        }
        
    }

}
