/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ValidationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ValidationApiTests
    {
        private ValidationApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ValidationApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ValidationApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ValidationApi
            //Assert.IsInstanceOfType(typeof(ValidationApi), instance, "instance is a ValidationApi");
        }

        
        /// <summary>
        /// Test V1PaymentsValidationGet
        /// </summary>
        [Test]
        public void V1PaymentsValidationGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string transID = null;
            //int? sIdType = null;
            //string sIdNum = null;
            //string sFirstName = null;
            //string sLastName = null;
            //string bFirstName = null;
            //string bLastName = null;
            //string bCountry = null;
            //int? bAccType = null;
            //string bIssuerCode = null;
            //string bAccNum = null;
            //double? trxValue = null;
            //var response = instance.V1PaymentsValidationGet(transID, sIdType, sIdNum, sFirstName, sLastName, bFirstName, bLastName, bCountry, bAccType, bIssuerCode, bAccNum, trxValue);
            //Assert.IsInstanceOf<GetValidationModelResponse> (response, "response is GetValidationModelResponse");
        }
        
    }

}
