/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DoBillInquiryModelResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DoBillInquiryModelResponseTests
    {
        // TODO uncomment below to declare an instance variable for DoBillInquiryModelResponse
        //private DoBillInquiryModelResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DoBillInquiryModelResponse
            //instance = new DoBillInquiryModelResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DoBillInquiryModelResponse
        /// </summary>
        [Test]
        public void DoBillInquiryModelResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DoBillInquiryModelResponse
            //Assert.IsInstanceOfType<DoBillInquiryModelResponse> (instance, "variable 'instance' is a DoBillInquiryModelResponse");
        }


        /// <summary>
        /// Test the property 'InquiryStatus'
        /// </summary>
        [Test]
        public void InquiryStatusTest()
        {
            // TODO unit test for the property 'InquiryStatus'
        }
        /// <summary>
        /// Test the property 'TransID'
        /// </summary>
        [Test]
        public void TransIDTest()
        {
            // TODO unit test for the property 'TransID'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [Test]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }
        /// <summary>
        /// Test the property 'StatementDate'
        /// </summary>
        [Test]
        public void StatementDateTest()
        {
            // TODO unit test for the property 'StatementDate'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Test]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'BillType'
        /// </summary>
        [Test]
        public void BillTypeTest()
        {
            // TODO unit test for the property 'BillType'
        }
        /// <summary>
        /// Test the property 'CustomInfo1'
        /// </summary>
        [Test]
        public void CustomInfo1Test()
        {
            // TODO unit test for the property 'CustomInfo1'
        }
        /// <summary>
        /// Test the property 'CustomInfo2'
        /// </summary>
        [Test]
        public void CustomInfo2Test()
        {
            // TODO unit test for the property 'CustomInfo2'
        }
        /// <summary>
        /// Test the property 'CustomInfo3'
        /// </summary>
        [Test]
        public void CustomInfo3Test()
        {
            // TODO unit test for the property 'CustomInfo3'
        }
        /// <summary>
        /// Test the property 'CustomInfo4'
        /// </summary>
        [Test]
        public void CustomInfo4Test()
        {
            // TODO unit test for the property 'CustomInfo4'
        }
        /// <summary>
        /// Test the property 'CustomInfo5'
        /// </summary>
        [Test]
        public void CustomInfo5Test()
        {
            // TODO unit test for the property 'CustomInfo5'
        }
        /// <summary>
        /// Test the property 'CustomInfo6'
        /// </summary>
        [Test]
        public void CustomInfo6Test()
        {
            // TODO unit test for the property 'CustomInfo6'
        }
        /// <summary>
        /// Test the property 'CustomInfo7'
        /// </summary>
        [Test]
        public void CustomInfo7Test()
        {
            // TODO unit test for the property 'CustomInfo7'
        }
        /// <summary>
        /// Test the property 'CustomInfo8'
        /// </summary>
        [Test]
        public void CustomInfo8Test()
        {
            // TODO unit test for the property 'CustomInfo8'
        }
        /// <summary>
        /// Test the property 'CustomInfo9'
        /// </summary>
        [Test]
        public void CustomInfo9Test()
        {
            // TODO unit test for the property 'CustomInfo9'
        }
        /// <summary>
        /// Test the property 'CustomInfo10'
        /// </summary>
        [Test]
        public void CustomInfo10Test()
        {
            // TODO unit test for the property 'CustomInfo10'
        }

    }

}
