/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DoBillPaymentModelCreated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DoBillPaymentModelCreatedTests
    {
        // TODO uncomment below to declare an instance variable for DoBillPaymentModelCreated
        //private DoBillPaymentModelCreated instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DoBillPaymentModelCreated
            //instance = new DoBillPaymentModelCreated();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DoBillPaymentModelCreated
        /// </summary>
        [Test]
        public void DoBillPaymentModelCreatedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DoBillPaymentModelCreated
            //Assert.IsInstanceOfType<DoBillPaymentModelCreated> (instance, "variable 'instance' is a DoBillPaymentModelCreated");
        }


        /// <summary>
        /// Test the property 'UIDBranch'
        /// </summary>
        [Test]
        public void UIDBranchTest()
        {
            // TODO unit test for the property 'UIDBranch'
        }
        /// <summary>
        /// Test the property 'TransID'
        /// </summary>
        [Test]
        public void TransIDTest()
        {
            // TODO unit test for the property 'TransID'
        }
        /// <summary>
        /// Test the property 'SFirstName'
        /// </summary>
        [Test]
        public void SFirstNameTest()
        {
            // TODO unit test for the property 'SFirstName'
        }
        /// <summary>
        /// Test the property 'SLastName'
        /// </summary>
        [Test]
        public void SLastNameTest()
        {
            // TODO unit test for the property 'SLastName'
        }
        /// <summary>
        /// Test the property 'SIdType'
        /// </summary>
        [Test]
        public void SIdTypeTest()
        {
            // TODO unit test for the property 'SIdType'
        }
        /// <summary>
        /// Test the property 'SIdNum'
        /// </summary>
        [Test]
        public void SIdNumTest()
        {
            // TODO unit test for the property 'SIdNum'
        }
        /// <summary>
        /// Test the property 'SIdExpiry'
        /// </summary>
        [Test]
        public void SIdExpiryTest()
        {
            // TODO unit test for the property 'SIdExpiry'
        }
        /// <summary>
        /// Test the property 'SContactNum'
        /// </summary>
        [Test]
        public void SContactNumTest()
        {
            // TODO unit test for the property 'SContactNum'
        }
        /// <summary>
        /// Test the property 'SEmail'
        /// </summary>
        [Test]
        public void SEmailTest()
        {
            // TODO unit test for the property 'SEmail'
        }
        /// <summary>
        /// Test the property 'SCountry'
        /// </summary>
        [Test]
        public void SCountryTest()
        {
            // TODO unit test for the property 'SCountry'
        }
        /// <summary>
        /// Test the property 'SCurrency'
        /// </summary>
        [Test]
        public void SCurrencyTest()
        {
            // TODO unit test for the property 'SCurrency'
        }
        /// <summary>
        /// Test the property 'BCountry'
        /// </summary>
        [Test]
        public void BCountryTest()
        {
            // TODO unit test for the property 'BCountry'
        }
        /// <summary>
        /// Test the property 'BCurrency'
        /// </summary>
        [Test]
        public void BCurrencyTest()
        {
            // TODO unit test for the property 'BCurrency'
        }
        /// <summary>
        /// Test the property 'BAmount'
        /// </summary>
        [Test]
        public void BAmountTest()
        {
            // TODO unit test for the property 'BAmount'
        }
        /// <summary>
        /// Test the property 'BIssuerCode'
        /// </summary>
        [Test]
        public void BIssuerCodeTest()
        {
            // TODO unit test for the property 'BIssuerCode'
        }
        /// <summary>
        /// Test the property 'BAccNum'
        /// </summary>
        [Test]
        public void BAccNumTest()
        {
            // TODO unit test for the property 'BAccNum'
        }
        /// <summary>
        /// Test the property 'BBillNum'
        /// </summary>
        [Test]
        public void BBillNumTest()
        {
            // TODO unit test for the property 'BBillNum'
        }
        /// <summary>
        /// Test the property 'BAccName'
        /// </summary>
        [Test]
        public void BAccNameTest()
        {
            // TODO unit test for the property 'BAccName'
        }
        /// <summary>
        /// Test the property 'BStatementDate'
        /// </summary>
        [Test]
        public void BStatementDateTest()
        {
            // TODO unit test for the property 'BStatementDate'
        }
        /// <summary>
        /// Test the property 'BDueDate'
        /// </summary>
        [Test]
        public void BDueDateTest()
        {
            // TODO unit test for the property 'BDueDate'
        }
        /// <summary>
        /// Test the property 'BBillType'
        /// </summary>
        [Test]
        public void BBillTypeTest()
        {
            // TODO unit test for the property 'BBillType'
        }
        /// <summary>
        /// Test the property 'BCustomInfo1'
        /// </summary>
        [Test]
        public void BCustomInfo1Test()
        {
            // TODO unit test for the property 'BCustomInfo1'
        }
        /// <summary>
        /// Test the property 'BCustomInfo2'
        /// </summary>
        [Test]
        public void BCustomInfo2Test()
        {
            // TODO unit test for the property 'BCustomInfo2'
        }
        /// <summary>
        /// Test the property 'BCustomInfo3'
        /// </summary>
        [Test]
        public void BCustomInfo3Test()
        {
            // TODO unit test for the property 'BCustomInfo3'
        }
        /// <summary>
        /// Test the property 'BCustomInfo4'
        /// </summary>
        [Test]
        public void BCustomInfo4Test()
        {
            // TODO unit test for the property 'BCustomInfo4'
        }
        /// <summary>
        /// Test the property 'BCustomInfo5'
        /// </summary>
        [Test]
        public void BCustomInfo5Test()
        {
            // TODO unit test for the property 'BCustomInfo5'
        }
        /// <summary>
        /// Test the property 'BCustomInfo6'
        /// </summary>
        [Test]
        public void BCustomInfo6Test()
        {
            // TODO unit test for the property 'BCustomInfo6'
        }
        /// <summary>
        /// Test the property 'BCustomInfo7'
        /// </summary>
        [Test]
        public void BCustomInfo7Test()
        {
            // TODO unit test for the property 'BCustomInfo7'
        }
        /// <summary>
        /// Test the property 'BCustomInfo8'
        /// </summary>
        [Test]
        public void BCustomInfo8Test()
        {
            // TODO unit test for the property 'BCustomInfo8'
        }
        /// <summary>
        /// Test the property 'BCustomInfo9'
        /// </summary>
        [Test]
        public void BCustomInfo9Test()
        {
            // TODO unit test for the property 'BCustomInfo9'
        }
        /// <summary>
        /// Test the property 'BCustomInfo10'
        /// </summary>
        [Test]
        public void BCustomInfo10Test()
        {
            // TODO unit test for the property 'BCustomInfo10'
        }

    }

}
