/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DoCancellationModelDeleted
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DoCancellationModelDeletedTests
    {
        // TODO uncomment below to declare an instance variable for DoCancellationModelDeleted
        //private DoCancellationModelDeleted instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DoCancellationModelDeleted
            //instance = new DoCancellationModelDeleted();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DoCancellationModelDeleted
        /// </summary>
        [Test]
        public void DoCancellationModelDeletedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DoCancellationModelDeleted
            //Assert.IsInstanceOfType<DoCancellationModelDeleted> (instance, "variable 'instance' is a DoCancellationModelDeleted");
        }


        /// <summary>
        /// Test the property 'TrxStatus'
        /// </summary>
        [Test]
        public void TrxStatusTest()
        {
            // TODO unit test for the property 'TrxStatus'
        }
        /// <summary>
        /// Test the property 'CancelID'
        /// </summary>
        [Test]
        public void CancelIDTest()
        {
            // TODO unit test for the property 'CancelID'
        }
        /// <summary>
        /// Test the property 'TransID'
        /// </summary>
        [Test]
        public void TransIDTest()
        {
            // TODO unit test for the property 'TransID'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
