/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DoChangeNameModelUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DoChangeNameModelUpdateTests
    {
        // TODO uncomment below to declare an instance variable for DoChangeNameModelUpdate
        //private DoChangeNameModelUpdate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DoChangeNameModelUpdate
            //instance = new DoChangeNameModelUpdate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DoChangeNameModelUpdate
        /// </summary>
        [Test]
        public void DoChangeNameModelUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DoChangeNameModelUpdate
            //Assert.IsInstanceOfType<DoChangeNameModelUpdate> (instance, "variable 'instance' is a DoChangeNameModelUpdate");
        }


        /// <summary>
        /// Test the property 'BeneFirstName'
        /// </summary>
        [Test]
        public void BeneFirstNameTest()
        {
            // TODO unit test for the property 'BeneFirstName'
        }
        /// <summary>
        /// Test the property 'BeneLastName'
        /// </summary>
        [Test]
        public void BeneLastNameTest()
        {
            // TODO unit test for the property 'BeneLastName'
        }

    }

}
