/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DoTransferModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DoTransferModelTests
    {
        // TODO uncomment below to declare an instance variable for DoTransferModel
        //private DoTransferModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DoTransferModel
            //instance = new DoTransferModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DoTransferModel
        /// </summary>
        [Test]
        public void DoTransferModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DoTransferModel
            //Assert.IsInstanceOfType<DoTransferModel> (instance, "variable 'instance' is a DoTransferModel");
        }


        /// <summary>
        /// Test the property 'UIDBranch'
        /// </summary>
        [Test]
        public void UIDBranchTest()
        {
            // TODO unit test for the property 'UIDBranch'
        }
        /// <summary>
        /// Test the property 'TransID'
        /// </summary>
        [Test]
        public void TransIDTest()
        {
            // TODO unit test for the property 'TransID'
        }
        /// <summary>
        /// Test the property 'SFirstName'
        /// </summary>
        [Test]
        public void SFirstNameTest()
        {
            // TODO unit test for the property 'SFirstName'
        }
        /// <summary>
        /// Test the property 'SLastName'
        /// </summary>
        [Test]
        public void SLastNameTest()
        {
            // TODO unit test for the property 'SLastName'
        }
        /// <summary>
        /// Test the property 'SIdType'
        /// </summary>
        [Test]
        public void SIdTypeTest()
        {
            // TODO unit test for the property 'SIdType'
        }
        /// <summary>
        /// Test the property 'SIdNum'
        /// </summary>
        [Test]
        public void SIdNumTest()
        {
            // TODO unit test for the property 'SIdNum'
        }
        /// <summary>
        /// Test the property 'SIdExpiry'
        /// </summary>
        [Test]
        public void SIdExpiryTest()
        {
            // TODO unit test for the property 'SIdExpiry'
        }
        /// <summary>
        /// Test the property 'SContactNum'
        /// </summary>
        [Test]
        public void SContactNumTest()
        {
            // TODO unit test for the property 'SContactNum'
        }
        /// <summary>
        /// Test the property 'SOccupation'
        /// </summary>
        [Test]
        public void SOccupationTest()
        {
            // TODO unit test for the property 'SOccupation'
        }
        /// <summary>
        /// Test the property 'SFundSource'
        /// </summary>
        [Test]
        public void SFundSourceTest()
        {
            // TODO unit test for the property 'SFundSource'
        }
        /// <summary>
        /// Test the property 'SBirthDate'
        /// </summary>
        [Test]
        public void SBirthDateTest()
        {
            // TODO unit test for the property 'SBirthDate'
        }
        /// <summary>
        /// Test the property 'SEmail'
        /// </summary>
        [Test]
        public void SEmailTest()
        {
            // TODO unit test for the property 'SEmail'
        }
        /// <summary>
        /// Test the property 'SAddress'
        /// </summary>
        [Test]
        public void SAddressTest()
        {
            // TODO unit test for the property 'SAddress'
        }
        /// <summary>
        /// Test the property 'SCity'
        /// </summary>
        [Test]
        public void SCityTest()
        {
            // TODO unit test for the property 'SCity'
        }
        /// <summary>
        /// Test the property 'SPostCode'
        /// </summary>
        [Test]
        public void SPostCodeTest()
        {
            // TODO unit test for the property 'SPostCode'
        }
        /// <summary>
        /// Test the property 'SCountry'
        /// </summary>
        [Test]
        public void SCountryTest()
        {
            // TODO unit test for the property 'SCountry'
        }
        /// <summary>
        /// Test the property 'SCurrency'
        /// </summary>
        [Test]
        public void SCurrencyTest()
        {
            // TODO unit test for the property 'SCurrency'
        }
        /// <summary>
        /// Test the property 'BCountry'
        /// </summary>
        [Test]
        public void BCountryTest()
        {
            // TODO unit test for the property 'BCountry'
        }
        /// <summary>
        /// Test the property 'BCurrency'
        /// </summary>
        [Test]
        public void BCurrencyTest()
        {
            // TODO unit test for the property 'BCurrency'
        }
        /// <summary>
        /// Test the property 'TrxValue'
        /// </summary>
        [Test]
        public void TrxValueTest()
        {
            // TODO unit test for the property 'TrxValue'
        }
        /// <summary>
        /// Test the property 'BFirstName'
        /// </summary>
        [Test]
        public void BFirstNameTest()
        {
            // TODO unit test for the property 'BFirstName'
        }
        /// <summary>
        /// Test the property 'BLastName'
        /// </summary>
        [Test]
        public void BLastNameTest()
        {
            // TODO unit test for the property 'BLastName'
        }
        /// <summary>
        /// Test the property 'BAccType'
        /// </summary>
        [Test]
        public void BAccTypeTest()
        {
            // TODO unit test for the property 'BAccType'
        }
        /// <summary>
        /// Test the property 'BIssuerCode'
        /// </summary>
        [Test]
        public void BIssuerCodeTest()
        {
            // TODO unit test for the property 'BIssuerCode'
        }
        /// <summary>
        /// Test the property 'BankProvince'
        /// </summary>
        [Test]
        public void BankProvinceTest()
        {
            // TODO unit test for the property 'BankProvince'
        }
        /// <summary>
        /// Test the property 'BankCity'
        /// </summary>
        [Test]
        public void BankCityTest()
        {
            // TODO unit test for the property 'BankCity'
        }
        /// <summary>
        /// Test the property 'BankBranchName'
        /// </summary>
        [Test]
        public void BankBranchNameTest()
        {
            // TODO unit test for the property 'BankBranchName'
        }
        /// <summary>
        /// Test the property 'BankBranchCode'
        /// </summary>
        [Test]
        public void BankBranchCodeTest()
        {
            // TODO unit test for the property 'BankBranchCode'
        }
        /// <summary>
        /// Test the property 'BAccNum'
        /// </summary>
        [Test]
        public void BAccNumTest()
        {
            // TODO unit test for the property 'BAccNum'
        }
        /// <summary>
        /// Test the property 'BIdType'
        /// </summary>
        [Test]
        public void BIdTypeTest()
        {
            // TODO unit test for the property 'BIdType'
        }
        /// <summary>
        /// Test the property 'BIdNum'
        /// </summary>
        [Test]
        public void BIdNumTest()
        {
            // TODO unit test for the property 'BIdNum'
        }
        /// <summary>
        /// Test the property 'BContactNum'
        /// </summary>
        [Test]
        public void BContactNumTest()
        {
            // TODO unit test for the property 'BContactNum'
        }
        /// <summary>
        /// Test the property 'Relationship'
        /// </summary>
        [Test]
        public void RelationshipTest()
        {
            // TODO unit test for the property 'Relationship'
        }
        /// <summary>
        /// Test the property 'BAddress'
        /// </summary>
        [Test]
        public void BAddressTest()
        {
            // TODO unit test for the property 'BAddress'
        }
        /// <summary>
        /// Test the property 'BCity'
        /// </summary>
        [Test]
        public void BCityTest()
        {
            // TODO unit test for the property 'BCity'
        }
        /// <summary>
        /// Test the property 'BPostCode'
        /// </summary>
        [Test]
        public void BPostCodeTest()
        {
            // TODO unit test for the property 'BPostCode'
        }
        /// <summary>
        /// Test the property 'BEmail'
        /// </summary>
        [Test]
        public void BEmailTest()
        {
            // TODO unit test for the property 'BEmail'
        }
        /// <summary>
        /// Test the property 'BProvinceCode'
        /// </summary>
        [Test]
        public void BProvinceCodeTest()
        {
            // TODO unit test for the property 'BProvinceCode'
        }
        /// <summary>
        /// Test the property 'BRegencyCode'
        /// </summary>
        [Test]
        public void BRegencyCodeTest()
        {
            // TODO unit test for the property 'BRegencyCode'
        }
        /// <summary>
        /// Test the property 'BPayoutID'
        /// </summary>
        [Test]
        public void BPayoutIDTest()
        {
            // TODO unit test for the property 'BPayoutID'
        }
        /// <summary>
        /// Test the property 'BPayoutPIN'
        /// </summary>
        [Test]
        public void BPayoutPINTest()
        {
            // TODO unit test for the property 'BPayoutPIN'
        }
        /// <summary>
        /// Test the property 'SAmount'
        /// </summary>
        [Test]
        public void SAmountTest()
        {
            // TODO unit test for the property 'SAmount'
        }
        /// <summary>
        /// Test the property 'FRKey'
        /// </summary>
        [Test]
        public void FRKeyTest()
        {
            // TODO unit test for the property 'FRKey'
        }
        /// <summary>
        /// Test the property 'BPurposeCode'
        /// </summary>
        [Test]
        public void BPurposeCodeTest()
        {
            // TODO unit test for the property 'BPurposeCode'
        }

    }

}
