/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetBalanceModelResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetBalanceModelResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetBalanceModelResponse
        //private GetBalanceModelResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetBalanceModelResponse
            //instance = new GetBalanceModelResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetBalanceModelResponse
        /// </summary>
        [Test]
        public void GetBalanceModelResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetBalanceModelResponse
            //Assert.IsInstanceOfType<GetBalanceModelResponse> (instance, "variable 'instance' is a GetBalanceModelResponse");
        }


        /// <summary>
        /// Test the property 'LastBal'
        /// </summary>
        [Test]
        public void LastBalTest()
        {
            // TODO unit test for the property 'LastBal'
        }

    }

}
