/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetForexModelResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetForexModelResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetForexModelResponse
        //private GetForexModelResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetForexModelResponse
            //instance = new GetForexModelResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetForexModelResponse
        /// </summary>
        [Test]
        public void GetForexModelResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetForexModelResponse
            //Assert.IsInstanceOfType<GetForexModelResponse> (instance, "variable 'instance' is a GetForexModelResponse");
        }


        /// <summary>
        /// Test the property 'CurrFrom'
        /// </summary>
        [Test]
        public void CurrFromTest()
        {
            // TODO unit test for the property 'CurrFrom'
        }
        /// <summary>
        /// Test the property 'CurrTo'
        /// </summary>
        [Test]
        public void CurrToTest()
        {
            // TODO unit test for the property 'CurrTo'
        }
        /// <summary>
        /// Test the property 'CurrRate'
        /// </summary>
        [Test]
        public void CurrRateTest()
        {
            // TODO unit test for the property 'CurrRate'
        }
        /// <summary>
        /// Test the property 'FRKey'
        /// </summary>
        [Test]
        public void FRKeyTest()
        {
            // TODO unit test for the property 'FRKey'
        }
        /// <summary>
        /// Test the property 'ExpiryDatetime'
        /// </summary>
        [Test]
        public void ExpiryDatetimeTest()
        {
            // TODO unit test for the property 'ExpiryDatetime'
        }

    }

}
