/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetPayoutCodeModelCreated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetPayoutCodeModelCreatedTests
    {
        // TODO uncomment below to declare an instance variable for GetPayoutCodeModelCreated
        //private GetPayoutCodeModelCreated instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetPayoutCodeModelCreated
            //instance = new GetPayoutCodeModelCreated();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetPayoutCodeModelCreated
        /// </summary>
        [Test]
        public void GetPayoutCodeModelCreatedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetPayoutCodeModelCreated
            //Assert.IsInstanceOfType<GetPayoutCodeModelCreated> (instance, "variable 'instance' is a GetPayoutCodeModelCreated");
        }


        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Test]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'PreBookQty'
        /// </summary>
        [Test]
        public void PreBookQtyTest()
        {
            // TODO unit test for the property 'PreBookQty'
        }

    }

}
