/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetTrxStatusModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetTrxStatusModelTests
    {
        // TODO uncomment below to declare an instance variable for GetTrxStatusModel
        //private GetTrxStatusModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetTrxStatusModel
            //instance = new GetTrxStatusModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetTrxStatusModel
        /// </summary>
        [Test]
        public void GetTrxStatusModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetTrxStatusModel
            //Assert.IsInstanceOfType<GetTrxStatusModel> (instance, "variable 'instance' is a GetTrxStatusModel");
        }


        /// <summary>
        /// Test the property 'TrxStatus'
        /// </summary>
        [Test]
        public void TrxStatusTest()
        {
            // TODO unit test for the property 'TrxStatus'
        }
        /// <summary>
        /// Test the property 'GTN'
        /// </summary>
        [Test]
        public void GTNTest()
        {
            // TODO unit test for the property 'GTN'
        }
        /// <summary>
        /// Test the property 'TransID'
        /// </summary>
        [Test]
        public void TransIDTest()
        {
            // TODO unit test for the property 'TransID'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'PayoutID'
        /// </summary>
        [Test]
        public void PayoutIDTest()
        {
            // TODO unit test for the property 'PayoutID'
        }
        /// <summary>
        /// Test the property 'PayoutPIN'
        /// </summary>
        [Test]
        public void PayoutPINTest()
        {
            // TODO unit test for the property 'PayoutPIN'
        }
        /// <summary>
        /// Test the property 'PayoutStatus'
        /// </summary>
        [Test]
        public void PayoutStatusTest()
        {
            // TODO unit test for the property 'PayoutStatus'
        }
        /// <summary>
        /// Test the property 'PayoutStatusUpdateDate'
        /// </summary>
        [Test]
        public void PayoutStatusUpdateDateTest()
        {
            // TODO unit test for the property 'PayoutStatusUpdateDate'
        }
        /// <summary>
        /// Test the property 'StatusType'
        /// </summary>
        [Test]
        public void StatusTypeTest()
        {
            // TODO unit test for the property 'StatusType'
        }
        /// <summary>
        /// Test the property 'BAccType'
        /// </summary>
        [Test]
        public void BAccTypeTest()
        {
            // TODO unit test for the property 'BAccType'
        }

    }

}
