/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetValidationModelResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetValidationModelResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetValidationModelResponse
        //private GetValidationModelResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetValidationModelResponse
            //instance = new GetValidationModelResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetValidationModelResponse
        /// </summary>
        [Test]
        public void GetValidationModelResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetValidationModelResponse
            //Assert.IsInstanceOfType<GetValidationModelResponse> (instance, "variable 'instance' is a GetValidationModelResponse");
        }


        /// <summary>
        /// Test the property 'ValidateStatus'
        /// </summary>
        [Test]
        public void ValidateStatusTest()
        {
            // TODO unit test for the property 'ValidateStatus'
        }
        /// <summary>
        /// Test the property 'TransID'
        /// </summary>
        [Test]
        public void TransIDTest()
        {
            // TODO unit test for the property 'TransID'
        }
        /// <summary>
        /// Test the property 'BeneficiaryName'
        /// </summary>
        [Test]
        public void BeneficiaryNameTest()
        {
            // TODO unit test for the property 'BeneficiaryName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
