/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBeneficiariesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Request amendment on beneficiary name.
        /// </summary>
        /// <remarks>
        /// Sample request:                    PUT v1/payments/transfers/{GTN}/requests/{transID}/change-name
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="GTN">Transaction GTN number (14 characters)</param>
        /// <param name="transID">Unique transaction ID used by RSP in Cancellation method</param>
        /// <param name="changeNameModel"> (optional)</param>
        /// <returns></returns>
        void V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePut (string GTN, string transID, DoChangeNameModelUpdate changeNameModel = null);

        /// <summary>
        /// Request amendment on beneficiary name.
        /// </summary>
        /// <remarks>
        /// Sample request:                    PUT v1/payments/transfers/{GTN}/requests/{transID}/change-name
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="GTN">Transaction GTN number (14 characters)</param>
        /// <param name="transID">Unique transaction ID used by RSP in Cancellation method</param>
        /// <param name="changeNameModel"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePutWithHttpInfo (string GTN, string transID, DoChangeNameModelUpdate changeNameModel = null);
        /// <summary>
        /// To inquire the status of the amendment request request.
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET v1/payments/transfers/change-name/{changeID}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeID">14-character change ID</param>
        /// <returns>GetChangeNameStatusModelResponse</returns>
        GetChangeNameStatusModelResponse V1PaymentsTransfersChangeNameByChangeIDGet (string changeID);

        /// <summary>
        /// To inquire the status of the amendment request request.
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET v1/payments/transfers/change-name/{changeID}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeID">14-character change ID</param>
        /// <returns>ApiResponse of GetChangeNameStatusModelResponse</returns>
        ApiResponse<GetChangeNameStatusModelResponse> V1PaymentsTransfersChangeNameByChangeIDGetWithHttpInfo (string changeID);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Request amendment on beneficiary name.
        /// </summary>
        /// <remarks>
        /// Sample request:                    PUT v1/payments/transfers/{GTN}/requests/{transID}/change-name
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="GTN">Transaction GTN number (14 characters)</param>
        /// <param name="transID">Unique transaction ID used by RSP in Cancellation method</param>
        /// <param name="changeNameModel"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePutAsync (string GTN, string transID, DoChangeNameModelUpdate changeNameModel = null);

        /// <summary>
        /// Request amendment on beneficiary name.
        /// </summary>
        /// <remarks>
        /// Sample request:                    PUT v1/payments/transfers/{GTN}/requests/{transID}/change-name
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="GTN">Transaction GTN number (14 characters)</param>
        /// <param name="transID">Unique transaction ID used by RSP in Cancellation method</param>
        /// <param name="changeNameModel"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePutAsyncWithHttpInfo (string GTN, string transID, DoChangeNameModelUpdate changeNameModel = null);
        /// <summary>
        /// To inquire the status of the amendment request request.
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET v1/payments/transfers/change-name/{changeID}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeID">14-character change ID</param>
        /// <returns>Task of GetChangeNameStatusModelResponse</returns>
        System.Threading.Tasks.Task<GetChangeNameStatusModelResponse> V1PaymentsTransfersChangeNameByChangeIDGetAsync (string changeID);

        /// <summary>
        /// To inquire the status of the amendment request request.
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET v1/payments/transfers/change-name/{changeID}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeID">14-character change ID</param>
        /// <returns>Task of ApiResponse (GetChangeNameStatusModelResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetChangeNameStatusModelResponse>> V1PaymentsTransfersChangeNameByChangeIDGetAsyncWithHttpInfo (string changeID);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BeneficiariesApi : IBeneficiariesApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BeneficiariesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BeneficiariesApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BeneficiariesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public BeneficiariesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Request amendment on beneficiary name. Sample request:                    PUT v1/payments/transfers/{GTN}/requests/{transID}/change-name
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="GTN">Transaction GTN number (14 characters)</param>
        /// <param name="transID">Unique transaction ID used by RSP in Cancellation method</param>
        /// <param name="changeNameModel"> (optional)</param>
        /// <returns></returns>
        public void V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePut (string GTN, string transID, DoChangeNameModelUpdate changeNameModel = null)
        {
             V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePutWithHttpInfo(GTN, transID, changeNameModel);
        }

        /// <summary>
        /// Request amendment on beneficiary name. Sample request:                    PUT v1/payments/transfers/{GTN}/requests/{transID}/change-name
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="GTN">Transaction GTN number (14 characters)</param>
        /// <param name="transID">Unique transaction ID used by RSP in Cancellation method</param>
        /// <param name="changeNameModel"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePutWithHttpInfo (string GTN, string transID, DoChangeNameModelUpdate changeNameModel = null)
        {
            // verify the required parameter 'GTN' is set
            if (GTN == null)
                throw new ApiException(400, "Missing required parameter 'GTN' when calling BeneficiariesApi->V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePut");
            // verify the required parameter 'transID' is set
            if (transID == null)
                throw new ApiException(400, "Missing required parameter 'transID' when calling BeneficiariesApi->V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePut");

            var localVarPath = "/v1/payments/transfers/{GTN}/requests/{transID}/change-name";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (GTN != null) localVarPathParams.Add("GTN", Configuration.ApiClient.ParameterToString(GTN)); // path parameter
            if (transID != null) localVarPathParams.Add("transID", Configuration.ApiClient.ParameterToString(transID)); // path parameter
            if (changeNameModel != null && changeNameModel.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(changeNameModel); // http body (model) parameter
            }
            else
            {
                localVarPostBody = changeNameModel; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Request amendment on beneficiary name. Sample request:                    PUT v1/payments/transfers/{GTN}/requests/{transID}/change-name
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="GTN">Transaction GTN number (14 characters)</param>
        /// <param name="transID">Unique transaction ID used by RSP in Cancellation method</param>
        /// <param name="changeNameModel"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePutAsync (string GTN, string transID, DoChangeNameModelUpdate changeNameModel = null)
        {
             await V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePutAsyncWithHttpInfo(GTN, transID, changeNameModel);

        }

        /// <summary>
        /// Request amendment on beneficiary name. Sample request:                    PUT v1/payments/transfers/{GTN}/requests/{transID}/change-name
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="GTN">Transaction GTN number (14 characters)</param>
        /// <param name="transID">Unique transaction ID used by RSP in Cancellation method</param>
        /// <param name="changeNameModel"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePutAsyncWithHttpInfo (string GTN, string transID, DoChangeNameModelUpdate changeNameModel = null)
        {
            // verify the required parameter 'GTN' is set
            if (GTN == null)
                throw new ApiException(400, "Missing required parameter 'GTN' when calling BeneficiariesApi->V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePut");
            // verify the required parameter 'transID' is set
            if (transID == null)
                throw new ApiException(400, "Missing required parameter 'transID' when calling BeneficiariesApi->V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePut");

            var localVarPath = "/v1/payments/transfers/{GTN}/requests/{transID}/change-name";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (GTN != null) localVarPathParams.Add("GTN", Configuration.ApiClient.ParameterToString(GTN)); // path parameter
            if (transID != null) localVarPathParams.Add("transID", Configuration.ApiClient.ParameterToString(transID)); // path parameter
            if (changeNameModel != null && changeNameModel.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(changeNameModel); // http body (model) parameter
            }
            else
            {
                localVarPostBody = changeNameModel; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1PaymentsTransfersByGTNRequestsByTransIDChangeNamePut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// To inquire the status of the amendment request request. Sample request:                    GET v1/payments/transfers/change-name/{changeID}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeID">14-character change ID</param>
        /// <returns>GetChangeNameStatusModelResponse</returns>
        public GetChangeNameStatusModelResponse V1PaymentsTransfersChangeNameByChangeIDGet (string changeID)
        {
             ApiResponse<GetChangeNameStatusModelResponse> localVarResponse = V1PaymentsTransfersChangeNameByChangeIDGetWithHttpInfo(changeID);
             return localVarResponse.Data;
        }

        /// <summary>
        /// To inquire the status of the amendment request request. Sample request:                    GET v1/payments/transfers/change-name/{changeID}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeID">14-character change ID</param>
        /// <returns>ApiResponse of GetChangeNameStatusModelResponse</returns>
        public ApiResponse< GetChangeNameStatusModelResponse > V1PaymentsTransfersChangeNameByChangeIDGetWithHttpInfo (string changeID)
        {
            // verify the required parameter 'changeID' is set
            if (changeID == null)
                throw new ApiException(400, "Missing required parameter 'changeID' when calling BeneficiariesApi->V1PaymentsTransfersChangeNameByChangeIDGet");

            var localVarPath = "/v1/payments/transfers/change-name/{changeID}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (changeID != null) localVarPathParams.Add("changeID", Configuration.ApiClient.ParameterToString(changeID)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1PaymentsTransfersChangeNameByChangeIDGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetChangeNameStatusModelResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetChangeNameStatusModelResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetChangeNameStatusModelResponse)));
        }

        /// <summary>
        /// To inquire the status of the amendment request request. Sample request:                    GET v1/payments/transfers/change-name/{changeID}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeID">14-character change ID</param>
        /// <returns>Task of GetChangeNameStatusModelResponse</returns>
        public async System.Threading.Tasks.Task<GetChangeNameStatusModelResponse> V1PaymentsTransfersChangeNameByChangeIDGetAsync (string changeID)
        {
             ApiResponse<GetChangeNameStatusModelResponse> localVarResponse = await V1PaymentsTransfersChangeNameByChangeIDGetAsyncWithHttpInfo(changeID);
             return localVarResponse.Data;

        }

        /// <summary>
        /// To inquire the status of the amendment request request. Sample request:                    GET v1/payments/transfers/change-name/{changeID}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="changeID">14-character change ID</param>
        /// <returns>Task of ApiResponse (GetChangeNameStatusModelResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GetChangeNameStatusModelResponse>> V1PaymentsTransfersChangeNameByChangeIDGetAsyncWithHttpInfo (string changeID)
        {
            // verify the required parameter 'changeID' is set
            if (changeID == null)
                throw new ApiException(400, "Missing required parameter 'changeID' when calling BeneficiariesApi->V1PaymentsTransfersChangeNameByChangeIDGet");

            var localVarPath = "/v1/payments/transfers/change-name/{changeID}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (changeID != null) localVarPathParams.Add("changeID", Configuration.ApiClient.ParameterToString(changeID)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1PaymentsTransfersChangeNameByChangeIDGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetChangeNameStatusModelResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetChangeNameStatusModelResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetChangeNameStatusModelResponse)));
        }

    }
}
