/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFeesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get fee that will be deduct for each transaction base on various currency and transaction amount.
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /v1/payments/fees?bAccType&#x3D;{bAccType}&amp;amp;currFrom&#x3D;{currFrom}&amp;amp;currTo&#x3D;{currTo}&amp;amp;trxValue&#x3D;{trxValue}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bAccType">Beneficiary Account Type (optional)</param>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <param name="trxValue">Total Amount is sent according to Beneficiary currency. It can be specified with any amount (optional)</param>
        /// <returns>GetTrxFeeModelResponse</returns>
        GetTrxFeeModelResponse V1PaymentsFeesGet (int? bAccType = null, string currFrom = null, string currTo = null, double? trxValue = null);

        /// <summary>
        /// Get fee that will be deduct for each transaction base on various currency and transaction amount.
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /v1/payments/fees?bAccType&#x3D;{bAccType}&amp;amp;currFrom&#x3D;{currFrom}&amp;amp;currTo&#x3D;{currTo}&amp;amp;trxValue&#x3D;{trxValue}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bAccType">Beneficiary Account Type (optional)</param>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <param name="trxValue">Total Amount is sent according to Beneficiary currency. It can be specified with any amount (optional)</param>
        /// <returns>ApiResponse of GetTrxFeeModelResponse</returns>
        ApiResponse<GetTrxFeeModelResponse> V1PaymentsFeesGetWithHttpInfo (int? bAccType = null, string currFrom = null, string currTo = null, double? trxValue = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get fee that will be deduct for each transaction base on various currency and transaction amount.
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /v1/payments/fees?bAccType&#x3D;{bAccType}&amp;amp;currFrom&#x3D;{currFrom}&amp;amp;currTo&#x3D;{currTo}&amp;amp;trxValue&#x3D;{trxValue}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bAccType">Beneficiary Account Type (optional)</param>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <param name="trxValue">Total Amount is sent according to Beneficiary currency. It can be specified with any amount (optional)</param>
        /// <returns>Task of GetTrxFeeModelResponse</returns>
        System.Threading.Tasks.Task<GetTrxFeeModelResponse> V1PaymentsFeesGetAsync (int? bAccType = null, string currFrom = null, string currTo = null, double? trxValue = null);

        /// <summary>
        /// Get fee that will be deduct for each transaction base on various currency and transaction amount.
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /v1/payments/fees?bAccType&#x3D;{bAccType}&amp;amp;currFrom&#x3D;{currFrom}&amp;amp;currTo&#x3D;{currTo}&amp;amp;trxValue&#x3D;{trxValue}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bAccType">Beneficiary Account Type (optional)</param>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <param name="trxValue">Total Amount is sent according to Beneficiary currency. It can be specified with any amount (optional)</param>
        /// <returns>Task of ApiResponse (GetTrxFeeModelResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetTrxFeeModelResponse>> V1PaymentsFeesGetAsyncWithHttpInfo (int? bAccType = null, string currFrom = null, string currTo = null, double? trxValue = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FeesApi : IFeesApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FeesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FeesApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FeesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FeesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get fee that will be deduct for each transaction base on various currency and transaction amount. Sample request:                    GET /v1/payments/fees?bAccType&#x3D;{bAccType}&amp;amp;currFrom&#x3D;{currFrom}&amp;amp;currTo&#x3D;{currTo}&amp;amp;trxValue&#x3D;{trxValue}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bAccType">Beneficiary Account Type (optional)</param>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <param name="trxValue">Total Amount is sent according to Beneficiary currency. It can be specified with any amount (optional)</param>
        /// <returns>GetTrxFeeModelResponse</returns>
        public GetTrxFeeModelResponse V1PaymentsFeesGet (int? bAccType = null, string currFrom = null, string currTo = null, double? trxValue = null)
        {
             ApiResponse<GetTrxFeeModelResponse> localVarResponse = V1PaymentsFeesGetWithHttpInfo(bAccType, currFrom, currTo, trxValue);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get fee that will be deduct for each transaction base on various currency and transaction amount. Sample request:                    GET /v1/payments/fees?bAccType&#x3D;{bAccType}&amp;amp;currFrom&#x3D;{currFrom}&amp;amp;currTo&#x3D;{currTo}&amp;amp;trxValue&#x3D;{trxValue}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bAccType">Beneficiary Account Type (optional)</param>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <param name="trxValue">Total Amount is sent according to Beneficiary currency. It can be specified with any amount (optional)</param>
        /// <returns>ApiResponse of GetTrxFeeModelResponse</returns>
        public ApiResponse< GetTrxFeeModelResponse > V1PaymentsFeesGetWithHttpInfo (int? bAccType = null, string currFrom = null, string currTo = null, double? trxValue = null)
        {

            var localVarPath = "/v1/payments/fees";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bAccType != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "bAccType", bAccType)); // query parameter
            if (currFrom != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "currFrom", currFrom)); // query parameter
            if (currTo != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "currTo", currTo)); // query parameter
            if (trxValue != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "trxValue", trxValue)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1PaymentsFeesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetTrxFeeModelResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetTrxFeeModelResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetTrxFeeModelResponse)));
        }

        /// <summary>
        /// Get fee that will be deduct for each transaction base on various currency and transaction amount. Sample request:                    GET /v1/payments/fees?bAccType&#x3D;{bAccType}&amp;amp;currFrom&#x3D;{currFrom}&amp;amp;currTo&#x3D;{currTo}&amp;amp;trxValue&#x3D;{trxValue}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bAccType">Beneficiary Account Type (optional)</param>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <param name="trxValue">Total Amount is sent according to Beneficiary currency. It can be specified with any amount (optional)</param>
        /// <returns>Task of GetTrxFeeModelResponse</returns>
        public async System.Threading.Tasks.Task<GetTrxFeeModelResponse> V1PaymentsFeesGetAsync (int? bAccType = null, string currFrom = null, string currTo = null, double? trxValue = null)
        {
             ApiResponse<GetTrxFeeModelResponse> localVarResponse = await V1PaymentsFeesGetAsyncWithHttpInfo(bAccType, currFrom, currTo, trxValue);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get fee that will be deduct for each transaction base on various currency and transaction amount. Sample request:                    GET /v1/payments/fees?bAccType&#x3D;{bAccType}&amp;amp;currFrom&#x3D;{currFrom}&amp;amp;currTo&#x3D;{currTo}&amp;amp;trxValue&#x3D;{trxValue}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bAccType">Beneficiary Account Type (optional)</param>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <param name="trxValue">Total Amount is sent according to Beneficiary currency. It can be specified with any amount (optional)</param>
        /// <returns>Task of ApiResponse (GetTrxFeeModelResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GetTrxFeeModelResponse>> V1PaymentsFeesGetAsyncWithHttpInfo (int? bAccType = null, string currFrom = null, string currTo = null, double? trxValue = null)
        {

            var localVarPath = "/v1/payments/fees";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (bAccType != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "bAccType", bAccType)); // query parameter
            if (currFrom != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "currFrom", currFrom)); // query parameter
            if (currTo != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "currTo", currTo)); // query parameter
            if (trxValue != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "trxValue", trxValue)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1PaymentsFeesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetTrxFeeModelResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetTrxFeeModelResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetTrxFeeModelResponse)));
        }

    }
}
