/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IForexApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Retrieve the GloRemit scheduled next rate with the effective date time when the new rate will apply
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /v1/payments/forex/nextrates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>GetForexModelResponse</returns>
        GetForexModelResponse V1PaymentsForexNextratesGet (string currFrom = null, string currTo = null);

        /// <summary>
        /// Retrieve the GloRemit scheduled next rate with the effective date time when the new rate will apply
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /v1/payments/forex/nextrates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>ApiResponse of GetForexModelResponse</returns>
        ApiResponse<GetForexModelResponse> V1PaymentsForexNextratesGetWithHttpInfo (string currFrom = null, string currTo = null);
        /// <summary>
        /// Retrieve the GloRemit quoted forex rate
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /v1/forex/rates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>GetForexModelResponse</returns>
        GetForexModelResponse V1PaymentsForexRatesGet (string currFrom = null, string currTo = null);

        /// <summary>
        /// Retrieve the GloRemit quoted forex rate
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /v1/forex/rates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>ApiResponse of GetForexModelResponse</returns>
        ApiResponse<GetForexModelResponse> V1PaymentsForexRatesGetWithHttpInfo (string currFrom = null, string currTo = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Retrieve the GloRemit scheduled next rate with the effective date time when the new rate will apply
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /v1/payments/forex/nextrates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>Task of GetForexModelResponse</returns>
        System.Threading.Tasks.Task<GetForexModelResponse> V1PaymentsForexNextratesGetAsync (string currFrom = null, string currTo = null);

        /// <summary>
        /// Retrieve the GloRemit scheduled next rate with the effective date time when the new rate will apply
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /v1/payments/forex/nextrates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>Task of ApiResponse (GetForexModelResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetForexModelResponse>> V1PaymentsForexNextratesGetAsyncWithHttpInfo (string currFrom = null, string currTo = null);
        /// <summary>
        /// Retrieve the GloRemit quoted forex rate
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /v1/forex/rates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>Task of GetForexModelResponse</returns>
        System.Threading.Tasks.Task<GetForexModelResponse> V1PaymentsForexRatesGetAsync (string currFrom = null, string currTo = null);

        /// <summary>
        /// Retrieve the GloRemit quoted forex rate
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /v1/forex/rates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>Task of ApiResponse (GetForexModelResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetForexModelResponse>> V1PaymentsForexRatesGetAsyncWithHttpInfo (string currFrom = null, string currTo = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ForexApi : IForexApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ForexApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ForexApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ForexApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ForexApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Retrieve the GloRemit scheduled next rate with the effective date time when the new rate will apply Sample request:                    GET /v1/payments/forex/nextrates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>GetForexModelResponse</returns>
        public GetForexModelResponse V1PaymentsForexNextratesGet (string currFrom = null, string currTo = null)
        {
             ApiResponse<GetForexModelResponse> localVarResponse = V1PaymentsForexNextratesGetWithHttpInfo(currFrom, currTo);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve the GloRemit scheduled next rate with the effective date time when the new rate will apply Sample request:                    GET /v1/payments/forex/nextrates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>ApiResponse of GetForexModelResponse</returns>
        public ApiResponse< GetForexModelResponse > V1PaymentsForexNextratesGetWithHttpInfo (string currFrom = null, string currTo = null)
        {

            var localVarPath = "/v1/payments/forex/nextrates";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (currFrom != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "CurrFrom", currFrom)); // query parameter
            if (currTo != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "CurrTo", currTo)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1PaymentsForexNextratesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetForexModelResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetForexModelResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetForexModelResponse)));
        }

        /// <summary>
        /// Retrieve the GloRemit scheduled next rate with the effective date time when the new rate will apply Sample request:                    GET /v1/payments/forex/nextrates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>Task of GetForexModelResponse</returns>
        public async System.Threading.Tasks.Task<GetForexModelResponse> V1PaymentsForexNextratesGetAsync (string currFrom = null, string currTo = null)
        {
             ApiResponse<GetForexModelResponse> localVarResponse = await V1PaymentsForexNextratesGetAsyncWithHttpInfo(currFrom, currTo);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve the GloRemit scheduled next rate with the effective date time when the new rate will apply Sample request:                    GET /v1/payments/forex/nextrates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>Task of ApiResponse (GetForexModelResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GetForexModelResponse>> V1PaymentsForexNextratesGetAsyncWithHttpInfo (string currFrom = null, string currTo = null)
        {

            var localVarPath = "/v1/payments/forex/nextrates";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (currFrom != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "CurrFrom", currFrom)); // query parameter
            if (currTo != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "CurrTo", currTo)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1PaymentsForexNextratesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetForexModelResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetForexModelResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetForexModelResponse)));
        }

        /// <summary>
        /// Retrieve the GloRemit quoted forex rate Sample request:                    GET /v1/forex/rates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>GetForexModelResponse</returns>
        public GetForexModelResponse V1PaymentsForexRatesGet (string currFrom = null, string currTo = null)
        {
             ApiResponse<GetForexModelResponse> localVarResponse = V1PaymentsForexRatesGetWithHttpInfo(currFrom, currTo);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve the GloRemit quoted forex rate Sample request:                    GET /v1/forex/rates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>ApiResponse of GetForexModelResponse</returns>
        public ApiResponse< GetForexModelResponse > V1PaymentsForexRatesGetWithHttpInfo (string currFrom = null, string currTo = null)
        {

            var localVarPath = "/v1/payments/forex/rates";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (currFrom != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "CurrFrom", currFrom)); // query parameter
            if (currTo != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "CurrTo", currTo)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1PaymentsForexRatesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetForexModelResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetForexModelResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetForexModelResponse)));
        }

        /// <summary>
        /// Retrieve the GloRemit quoted forex rate Sample request:                    GET /v1/forex/rates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>Task of GetForexModelResponse</returns>
        public async System.Threading.Tasks.Task<GetForexModelResponse> V1PaymentsForexRatesGetAsync (string currFrom = null, string currTo = null)
        {
             ApiResponse<GetForexModelResponse> localVarResponse = await V1PaymentsForexRatesGetAsyncWithHttpInfo(currFrom, currTo);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve the GloRemit quoted forex rate Sample request:                    GET /v1/forex/rates?CurrFrom&#x3D;{CurrFrom}&amp;amp;CurrTo&#x3D;{CurrTo}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="currFrom">ISO 4217 Currency Code (Sell) (optional)</param>
        /// <param name="currTo">ISO 4217 Currency Code (Buy) (optional)</param>
        /// <returns>Task of ApiResponse (GetForexModelResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GetForexModelResponse>> V1PaymentsForexRatesGetAsyncWithHttpInfo (string currFrom = null, string currTo = null)
        {

            var localVarPath = "/v1/payments/forex/rates";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (currFrom != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "CurrFrom", currFrom)); // query parameter
            if (currTo != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "CurrTo", currTo)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1PaymentsForexRatesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetForexModelResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetForexModelResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetForexModelResponse)));
        }

    }
}
