/* 
 * GloRemit - REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISupportedEntitiesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get list of the supported banks, cash pickup companies, billers, provinces and regencies.
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET v1/payments/supportedentities/{listname}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listname"></param>
        /// <returns>GetTrxFeeModelResponse</returns>
        GetTrxFeeModelResponse V1PaymentsSupportedentitiesByListnameGet (string listname);

        /// <summary>
        /// Get list of the supported banks, cash pickup companies, billers, provinces and regencies.
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET v1/payments/supportedentities/{listname}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listname"></param>
        /// <returns>ApiResponse of GetTrxFeeModelResponse</returns>
        ApiResponse<GetTrxFeeModelResponse> V1PaymentsSupportedentitiesByListnameGetWithHttpInfo (string listname);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get list of the supported banks, cash pickup companies, billers, provinces and regencies.
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET v1/payments/supportedentities/{listname}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listname"></param>
        /// <returns>Task of GetTrxFeeModelResponse</returns>
        System.Threading.Tasks.Task<GetTrxFeeModelResponse> V1PaymentsSupportedentitiesByListnameGetAsync (string listname);

        /// <summary>
        /// Get list of the supported banks, cash pickup companies, billers, provinces and regencies.
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET v1/payments/supportedentities/{listname}
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listname"></param>
        /// <returns>Task of ApiResponse (GetTrxFeeModelResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetTrxFeeModelResponse>> V1PaymentsSupportedentitiesByListnameGetAsyncWithHttpInfo (string listname);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SupportedEntitiesApi : ISupportedEntitiesApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SupportedEntitiesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SupportedEntitiesApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SupportedEntitiesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SupportedEntitiesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get list of the supported banks, cash pickup companies, billers, provinces and regencies. Sample request:                    GET v1/payments/supportedentities/{listname}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listname"></param>
        /// <returns>GetTrxFeeModelResponse</returns>
        public GetTrxFeeModelResponse V1PaymentsSupportedentitiesByListnameGet (string listname)
        {
             ApiResponse<GetTrxFeeModelResponse> localVarResponse = V1PaymentsSupportedentitiesByListnameGetWithHttpInfo(listname);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get list of the supported banks, cash pickup companies, billers, provinces and regencies. Sample request:                    GET v1/payments/supportedentities/{listname}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listname"></param>
        /// <returns>ApiResponse of GetTrxFeeModelResponse</returns>
        public ApiResponse< GetTrxFeeModelResponse > V1PaymentsSupportedentitiesByListnameGetWithHttpInfo (string listname)
        {
            // verify the required parameter 'listname' is set
            if (listname == null)
                throw new ApiException(400, "Missing required parameter 'listname' when calling SupportedEntitiesApi->V1PaymentsSupportedentitiesByListnameGet");

            var localVarPath = "/v1/payments/supportedentities/{listname}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (listname != null) localVarPathParams.Add("listname", Configuration.ApiClient.ParameterToString(listname)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1PaymentsSupportedentitiesByListnameGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetTrxFeeModelResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetTrxFeeModelResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetTrxFeeModelResponse)));
        }

        /// <summary>
        /// Get list of the supported banks, cash pickup companies, billers, provinces and regencies. Sample request:                    GET v1/payments/supportedentities/{listname}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listname"></param>
        /// <returns>Task of GetTrxFeeModelResponse</returns>
        public async System.Threading.Tasks.Task<GetTrxFeeModelResponse> V1PaymentsSupportedentitiesByListnameGetAsync (string listname)
        {
             ApiResponse<GetTrxFeeModelResponse> localVarResponse = await V1PaymentsSupportedentitiesByListnameGetAsyncWithHttpInfo(listname);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get list of the supported banks, cash pickup companies, billers, provinces and regencies. Sample request:                    GET v1/payments/supportedentities/{listname}
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="listname"></param>
        /// <returns>Task of ApiResponse (GetTrxFeeModelResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GetTrxFeeModelResponse>> V1PaymentsSupportedentitiesByListnameGetAsyncWithHttpInfo (string listname)
        {
            // verify the required parameter 'listname' is set
            if (listname == null)
                throw new ApiException(400, "Missing required parameter 'listname' when calling SupportedEntitiesApi->V1PaymentsSupportedentitiesByListnameGet");

            var localVarPath = "/v1/payments/supportedentities/{listname}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (listname != null) localVarPathParams.Add("listname", Configuration.ApiClient.ParameterToString(listname)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1PaymentsSupportedentitiesByListnameGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetTrxFeeModelResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GetTrxFeeModelResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetTrxFeeModelResponse)));
        }

    }
}
